### ISSUE TITLE
README.md中的说明方法调用函数参数与实际代码参数有错误

### ISSUE THREAD

**Issue by note520** [node-weixin/node-weixin-oauth#1]
6、检验token有效性(可选)

nwo.validate(openid, **refreshToken**, function(error, body) {
});
这里的refreshToken 是错误的，应该是accessToken。lib里的代码没错误，说明文档正确调用应该是

nwo.validate(openid,accessToken, function(bool) {
});

**Comment by calidion** [comment]
谢谢。欢迎发送PR给我。
