### ISSUE TITLE
设计有问题？

### ISSUE THREAD

**Issue by callmesoul** [node-weixin/node-weixin-oauth#4]
授权获得code后在通过success获得用户信息时已经刷新了acess_token，当我们再次获得用户openid，查对应之前的acess_token已经是的旧的了，没有方法自拿openid不刷新acess_token的么？
`nwo.success(app, code, function(error, body) {
  if (!error) {
    var accessToken = body.acess_token;
    var refreshToken = body.refresh_token;
  }
});`

**Comment by calidion** [comment]
openid应该在body里面，自己获取就可以了。
示例只是没有注明。
欢迎针对示例的问题PR给我你的意见。

**Comment by callmesoul** [comment]
我是说nwo.success已经刷新了token，旧的已经用不了，但要获得openid旧必须nwo.success

**Comment by calidion** [comment]
@callmesoul 

没理解你的意思。
如果是刷新请使用refresh.

如果有bug，欢迎PR.
谢谢。
